version: '3.8'

services:
  anc-server:
    build: .
    container_name: anc-server
    ports:
      - "17017:17017"
    volumes:
      - ./anchors:/app/anchors
    networks:
      - anc
    restart: unless-stopped

networks:
  anc:
    external: true

