#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="$(dirname "$0")/.env"

# ---------------------------------------------------------------------------
# 1. Generate .env if it doesn't exist
# ---------------------------------------------------------------------------
if [ ! -f "$ENV_FILE" ]; then
  echo ">> Generating secrets in .env (first run)..."
  cat > "$ENV_FILE" <<EOF
# Auto-generated by start.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Keep this file secret and do NOT commit it to version control.
JWT_SECRET=$(openssl rand -base64 32)
VAULT_MASTER_KEY=$(openssl rand -base64 32)
EOF
  echo "   .env created."
else
  echo ">> .env already exists — using existing secrets."
fi

# ---------------------------------------------------------------------------
# 2. Create Docker network if needed
# ---------------------------------------------------------------------------
if ! docker network inspect anc &>/dev/null; then
  echo ">> Creating Docker network 'anc'..."
  docker network create anc
fi

# ---------------------------------------------------------------------------
# 3. Bring up the stack
# ---------------------------------------------------------------------------
cd "$(dirname "$0")"
echo ">> Starting services..."
docker compose --env-file .env up -d --build

# ---------------------------------------------------------------------------
# 4. Wait for health
# ---------------------------------------------------------------------------
echo -n ">> Waiting for anc-server to be healthy"
for i in $(seq 1 30); do
  if curl -sf http://localhost:17017/health > /dev/null 2>&1; then
    echo " ok"
    break
  fi
  echo -n "."
  sleep 2
done

# ---------------------------------------------------------------------------
# 5. Summary
# ---------------------------------------------------------------------------
echo ""
echo "┌─────────────────────────────────────────────┐"
echo "│  Anchor Vault Server is up                  │"
echo "│                                             │"
echo "│  API:       http://localhost:17017          │"
echo "│  Docs:      http://localhost:17017/docs     │"
echo "│  Dashboard: http://localhost:17017/dashboard│"
echo "│  Health:    http://localhost:17017/health   │"
echo "└─────────────────────────────────────────────┘"
echo ""
echo "Next step — create your first admin user:"
echo ""
echo "  curl -X POST http://localhost:17017/admin/users \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"username\": \"admin\", \"password\": \"changeme\", \"groups\": [\"admins\"]}'"
echo ""
echo "  (This works without auth only if no users exist yet — see README for details)"
