"""
VPN commands — WireGuard tunnel management via SPA V2 (ECDH-based knock).

  anc vpn init <token> — save config from provision token (zero secrets)
  anc vpn up           — ECDH knock → onboarding tunnel → promote → full tunnel
  anc vpn down         — bring down the VPN tunnel and best-effort revoke server lease
  anc vpn status       — show server lease info + local wg show

First-time setup: 'anc vpn up' runs an interactive wizard that saves
~/.config/anchor/vpn.toml (mode 0600).

Dependencies (install with pip install 'anchor-cli[vpn]'):
  pycryptodome>=3   — AES-256-GCM for SPA packet
  cryptography>=41  — X25519 ECDH for key exchange
  qrcode>=7.4       — ASCII QR code in terminal (optional, falls back to URL)

External binaries (wireguard-tools, must be in PATH):
  wg, wg-quick      — WireGuard key generation and tunnel management
"""
from __future__ import annotations

import base64
import getpass
import json
import ipaddress
import os
import socket
import struct
import subprocess
import sys
import time
from pathlib import Path
from typing import Optional

import requests
import typer
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt
from rich.table import Table

from anchor.config import (
    CONFIG_DIR,
    ensure_dirs,
    load_credentials,
    save_credentials,
)
from anchor.client import AnchorClient, AnchorClientError, NotAuthenticatedError

console = Console()
app = typer.Typer(
    name="vpn",
    help="Manage WireGuard VPN tunnel via SPA.",
    no_args_is_help=True,
)

VPN_CONFIG_FILE = CONFIG_DIR / "vpn.toml"
WG_IFACE = "anc-vpn"
WG_CONF = Path("/tmp/anc-vpn.conf")


# ---------------------------------------------------------------------------
# VPN config helpers
# ---------------------------------------------------------------------------

def _load_vpn_config() -> dict:
    if not VPN_CONFIG_FILE.exists():
        return {}
    try:
        import tomllib  # stdlib 3.11+
    except ImportError:
        try:
            import tomli as tomllib  # type: ignore[no-redef]
        except ImportError:
            return {}
    with open(VPN_CONFIG_FILE, "rb") as f:
        return tomllib.load(f)


def _save_vpn_config(cfg: dict) -> None:
    ensure_dirs()
    VPN_CONFIG_FILE.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    for k, v in cfg.items():
        if isinstance(v, bool):
            lines.append(f"{k} = {'true' if v else 'false'}")
        elif isinstance(v, str):
            escaped = v.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'{k} = "{escaped}"')
        else:
            lines.append(f"{k} = {v}")
    VPN_CONFIG_FILE.write_text("\n".join(lines) + "\n")
    os.chmod(VPN_CONFIG_FILE, 0o600)


def _parse_provision_token(token: str) -> dict:
    """
    Decode a base64url provision token generated by POST /vpn/admin/users/{u}/otp.
    Returns the config dict or raises ValueError with a human-readable message.

    SPA V2 tokens contain ZERO secrets — only public/endpoint info + spa_pubkey.
    """
    try:
        # Add padding if needed
        padded = token + "=" * (4 - len(token) % 4)
        data = json.loads(base64.urlsafe_b64decode(padded))
    except Exception:
        raise ValueError("Invalid token — could not decode. Make sure you copied it completely.")

    required = {"uid", "vpn_uid", "knock_host", "knock_port", "spa_pubkey",
                "subnet", "server_vpn_uid", "server_endpoint", "server_pubkey", "server_port"}
    missing = required - set(data.keys())
    if missing:
        raise ValueError(f"Token is missing fields: {', '.join(sorted(missing))}")

    return data


def _run_wizard() -> dict:
    """
    Interactive first-time setup wizard.
    Primary path: paste the provision token the admin gave you (one field).
    Fallback: enter fields manually if you don't have a token.
    Returns the saved config dict.
    """
    console.print()
    console.print(Panel(
        "[bold]VPN First-Time Setup[/bold]\n\n"
        "Ask your admin to run:\n"
        "  [cyan]POST /vpn/admin/users/{tu_usuario}/otp[/cyan]\n\n"
        "Te dará un [bold]provision token[/bold]. Pégalo aquí y listo.\n"
        "El admin te enviará por separado la URL del QR para el TOTP.",
        title="[bold blue]anc vpn setup",
    ))
    console.print()

    token_raw = Prompt.ask("[cyan]Provision token (or press Enter for manual setup)")
    if token_raw.strip():
        try:
            cfg = _parse_provision_token(token_raw.strip())
        except ValueError as exc:
            console.print(f"[red]Token error:[/red] {exc}")
            raise typer.Exit(1)
        _save_vpn_config(cfg)
        console.print(f"[green]Config saved to[/green] {VPN_CONFIG_FILE}")
        console.print(
            "[dim]Ask the admin for the TOTP URL from the provision modal "
            "and run [bold]anc vpn init <token> '<otpauth://…>'[/bold] "
            "to display the QR code, then [bold]anc vpn up[/bold][/dim]"
        )
        return cfg

    # ── Manual fallback ──────────────────────────────────────────────────────
    console.print("[dim]Manual setup — ask your admin for each value.[/dim]\n")
    uid = Prompt.ask("[cyan]Your username")
    knock_host = Prompt.ask("[cyan]Knock server hostname or IP")
    knock_port = int(Prompt.ask("[cyan]Knock UDP port", default="62201"))
    spa_pubkey = Prompt.ask("[cyan]SPA public key (base64, from admin)")
    subnet = Prompt.ask("[cyan]VPN subnet", default="10.8.0.0/24")
    server_endpoint = Prompt.ask("[cyan]WireGuard server endpoint (host:port)")
    server_pubkey = Prompt.ask("[cyan]WireGuard server public key")
    server_port = int(Prompt.ask("[cyan]Anchor server internal port", default="17017"))

    console.print(
        "[yellow]vpn_uid unknown in manual mode.[/yellow] "
        "The correct IP will be set after the first successful 'anc vpn up'.\n"
        "If the first attempt times out, ask the admin for your numeric vpn_uid "
        "and set it manually in ~/.config/anchor/vpn.toml."
    )
    vpn_uid = int(Prompt.ask("[cyan]Your VPN UID (numeric, from admin; 0 = unknown)", default="0"))

    cfg = {
        "uid": uid,
        "vpn_uid": vpn_uid,
        "knock_host": knock_host,
        "knock_port": knock_port,
        "spa_pubkey": spa_pubkey,
        "subnet": subnet,
        "server_vpn_uid": 1,
        "server_endpoint": server_endpoint,
        "server_pubkey": server_pubkey,
        "server_port": server_port,
    }
    _save_vpn_config(cfg)
    console.print(f"[green]Config saved to[/green] {VPN_CONFIG_FILE}")
    return cfg


# ---------------------------------------------------------------------------
# Crypto helpers (replicates server/code/vpn/spa.py — no server deps in CLI)
# ---------------------------------------------------------------------------

def _check_vpn_deps() -> None:
    """Fail fast with a helpful message if optional VPN deps are missing."""
    missing = []
    try:
        from Crypto.Cipher import AES  # noqa: F401
    except ImportError:
        missing.append("pycryptodome")
    try:
        from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey  # noqa: F401
    except ImportError:
        missing.append("cryptography")
    if missing:
        console.print(
            f"[red]Missing VPN dependencies: {', '.join(missing)}[/red]\n"
            "Install with: [bold]pip install 'anchor-cli[vpn]'[/bold]"
        )
        raise typer.Exit(1)


def _show_qr(provisioning_url: str) -> None:
    """Print an ASCII QR code in the terminal for the TOTP provisioning URL."""
    try:
        import qrcode  # type: ignore[import]
        qr = qrcode.QRCode(border=1)
        qr.add_data(provisioning_url)
        qr.make(fit=True)
        console.print("\n[bold]Scan this QR with Google Authenticator / Authy:[/bold]")
        qr.print_ascii(invert=True)
        console.print()
    except ImportError:
        console.print(f"[dim]Provisioning URL:[/dim] {provisioning_url}")
        console.print("[dim](Install qrcode for a QR code in terminal)[/dim]")


def _uid_to_ip(uid: int, subnet: str) -> str:
    net = ipaddress.IPv4Network(subnet, strict=False)
    return str(net.network_address + uid)


def _build_spa_packet(
    vpn_uid: int,
    otp_str: str,
    wg_pubkey: str,
    spa_pubkey_b64: str,
) -> bytes:
    """
    Build the 126-byte SPA V2 UDP packet.
    Mirrors server/code/vpn/spa.py:build_packet() exactly.

    Uses X25519 ECDH: ephemeral keypair → shared secret → AES-256-GCM key.
    Zero secrets on the client — only the server's SPA public key is needed.
    """
    from Crypto.Cipher import AES
    from Crypto.Hash import SHA256
    from Crypto.Protocol.KDF import HKDF
    from Crypto.Random import get_random_bytes
    from cryptography.hazmat.primitives.asymmetric.x25519 import (
        X25519PrivateKey,
        X25519PublicKey,
    )

    VPN_UID_SIZE, NONCE_SIZE, OTP_SIZE, TS_SIZE, PUBKEY_SIZE = 4, 16, 6, 8, 44

    # Load server's SPA public key
    server_spa_pub = X25519PublicKey.from_public_bytes(base64.b64decode(spa_pubkey_b64))

    # Ephemeral ECDH keypair (forward secrecy)
    eph_priv = X25519PrivateKey.generate()
    eph_pub_bytes = eph_priv.public_key().public_bytes_raw()  # 32 bytes

    # Shared secret → AES key
    shared = eph_priv.exchange(server_spa_pub)
    key = HKDF(
        master=shared,
        key_len=32,
        salt=b"spa-v2",
        hashmod=SHA256,
    )

    # Build plaintext: vpn_uid(4) + otp(6) + timestamp(8) + wg_pubkey(44) = 62
    ts = int(time.time())
    plaintext = (
        struct.pack(">I", vpn_uid)
        + otp_str.encode().ljust(OTP_SIZE, b"\x00")[:OTP_SIZE]
        + struct.pack(">Q", ts)
        + wg_pubkey.encode().ljust(PUBKEY_SIZE, b"\x00")[:PUBKEY_SIZE]
    )

    # AES-256-GCM encrypt
    nonce = get_random_bytes(NONCE_SIZE)
    cipher = AES.new(key, AES.MODE_GCM, nonce=nonce)
    ciphertext, tag = cipher.encrypt_and_digest(plaintext)

    return eph_pub_bytes + nonce + ciphertext + tag


# ---------------------------------------------------------------------------
# JWT helpers
# ---------------------------------------------------------------------------

def _decode_jwt_exp(token: str) -> int:
    """Return JWT exp claim (Unix timestamp), or 0 on failure."""
    try:
        parts = token.split(".")
        if len(parts) != 3:
            return 0
        padding = 4 - len(parts[1]) % 4
        payload = json.loads(base64.b64decode(parts[1] + "=" * padding))
        return int(payload.get("exp", 0))
    except Exception:
        return 0


def _token_valid(token: str) -> bool:
    return time.time() < _decode_jwt_exp(token) - 30  # 30 s buffer


def _do_login(server_url: str, username: str) -> Optional[str]:
    """Prompt for password, POST /auth/login, return JWT or None."""
    try:
        password = getpass.getpass(f"Password for {username}: ")
        resp = requests.post(
            f"{server_url.rstrip('/')}/auth/login",
            json={"username": username, "password": password},
            timeout=10,
        )
        if resp.status_code == 200:
            return resp.json().get("access_token")
        console.print(f"[red]Login failed:[/red] {resp.json().get('detail', resp.status_code)}")
    except Exception as exc:
        console.print(f"[red]Login error:[/red] {exc}")
    return None


# ---------------------------------------------------------------------------
# WireGuard helpers
# ---------------------------------------------------------------------------

def _wg_genkey() -> tuple[str, str]:
    """Generate a WireGuard keypair. Returns (privkey, pubkey) strings."""
    try:
        privkey = subprocess.check_output(
            ["wg", "genkey"], stderr=subprocess.DEVNULL
        ).decode().strip()
        pubkey = subprocess.check_output(
            ["wg", "pubkey"], input=privkey.encode(), stderr=subprocess.DEVNULL
        ).decode().strip()
        return privkey, pubkey
    except FileNotFoundError:
        console.print("[red]'wg' not found. Install wireguard-tools.[/red]")
        raise typer.Exit(1)
    except subprocess.CalledProcessError as exc:
        console.print(f"[red]Key generation failed:[/red] {exc}")
        raise typer.Exit(1)


def _wg_quick(action: str, target: str, check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["sudo", "wg-quick", action, target],
        capture_output=True, text=True, check=check,
    )


def _wait_for_handshake(timeout: float = 10.0, interval: float = 0.5) -> bool:
    """Poll wg show until a handshake timestamp > 0 is seen."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        result = subprocess.run(
            ["sudo", "wg", "show", WG_IFACE, "latest-handshakes"],
            capture_output=True, text=True,
        )
        if result.returncode == 0:
            for line in result.stdout.strip().splitlines():
                parts = line.split()
                if len(parts) >= 2 and int(parts[-1]) > 0:
                    return True
        time.sleep(interval)
    return False


def _write_wg_conf(
    privkey: str,
    my_ip: str,
    server_pubkey: str,
    server_endpoint: str,
    allowed_ips: str,
    dns: str = "",
) -> None:
    dns_line = f"DNS = {dns}\n" if dns else ""
    WG_CONF.write_text(
        f"[Interface]\n"
        f"PrivateKey = {privkey}\n"
        f"Address = {my_ip}/32\n"
        f"{dns_line}"
        f"\n"
        f"[Peer]\n"
        f"PublicKey = {server_pubkey}\n"
        f"Endpoint = {server_endpoint}\n"
        f"AllowedIPs = {allowed_ips}\n"
        f"PersistentKeepalive = 25\n"
    )
    os.chmod(WG_CONF, 0o600)


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------

@app.command("init")
def vpn_init(
    token: str = typer.Argument(..., help="Provision token from POST /vpn/admin/users/{u}/otp"),
    provisioning_url: Optional[str] = typer.Argument(
        None,
        help="TOTP provisioning URL (otpauth://…) from the admin's provision modal — shows QR.",
    ),
) -> None:
    """
    Save VPN config from a provision token, then optionally display the TOTP QR.

    The admin runs 'POST /vpn/admin/users/{you}/otp' via the web UI, which
    shows TWO things in the provision modal:
      1. The 'provision_token'  → paste as the first argument here.
      2. The 'TOTP URL'         → paste as the second argument to get a QR code
                                   you can scan with Google Authenticator / Authy.

    The token contains ZERO secrets.  The TOTP seed lives only on the server.

    Examples:
      # Config only (scan TOTP separately):
      anc vpn init eyJ1aWQiOiJhbGljZSIsInZwbl91aWQiOjIs...

      # Config + QR code in one step:
      anc vpn init eyJ1aWQiOiJhbGljZSIsInZwbl91aWQiOjIs... 'otpauth://totp/...'

      anc vpn up
    """
    try:
        cfg = _parse_provision_token(token.strip())
    except ValueError as exc:
        console.print(f"[red]Token error:[/red] {exc}")
        raise typer.Exit(1)

    _save_vpn_config(cfg)
    ip_hint = _uid_to_ip(cfg["vpn_uid"], cfg["subnet"])
    console.print(
        f"[green]VPN configured for user[/green] [bold]{cfg['uid']}[/bold] "
        f"[dim](expected IP: {ip_hint})[/dim]\n"
        f"Config saved to {VPN_CONFIG_FILE}"
    )

    if provisioning_url and provisioning_url.strip():
        _show_qr(provisioning_url.strip())
    else:
        console.print(
            "\n[dim]Add the TOTP secret to your authenticator app:[/dim]\n"
            "  Ask the admin for the TOTP URL from the provision modal, then run:\n"
            "  [bold]anc vpn init <token> '<otpauth://totp/...>'[/bold]\n"
            "  or scan the QR from the web UI directly."
        )

    console.print("\nRun [bold]anc vpn up[/bold] to connect.")


@app.command("up")
def vpn_up(
    totp_code: Optional[str] = typer.Argument(
        None,
        help="6-digit TOTP from your authenticator app. Prompted interactively if not given.",
    ),
) -> None:
    """
    Bring up the WireGuard VPN tunnel via SPA V2 knock.

    Flow: generate ephemeral WG keypair → ECDH knock → onboarding tunnel →
    authenticate → promote → full tunnel with routes.
    """
    _check_vpn_deps()

    # ── 1. Read / create config ──────────────────────────────────────────────
    cfg = _load_vpn_config()
    if not cfg:
        cfg = _run_wizard()

    uid: str = cfg["uid"]
    subnet: str = cfg.get("subnet", "10.8.0.0/24")
    server_vpn_uid: int = int(cfg.get("server_vpn_uid", 1))
    server_port: int = int(cfg.get("server_port", 17017))
    my_vpn_uid: int = int(cfg.get("vpn_uid", 0))
    server_endpoint_cfg: str = cfg["server_endpoint"]
    server_pubkey_cfg: str = cfg["server_pubkey"]
    spa_pubkey_b64: str = cfg["spa_pubkey"]
    knock_host: str = cfg["knock_host"]
    knock_port: int = int(cfg.get("knock_port", 62201))

    server_vpn_ip = _uid_to_ip(server_vpn_uid, subnet)

    # IP: derive from vpn_uid
    if my_vpn_uid > 0:
        my_ip_str = _uid_to_ip(my_vpn_uid, subnet)
    else:
        console.print(
            "[yellow]vpn_uid not set — using placeholder IP.[/yellow]\n"
            "Ask the admin for 'anc vpn init <token>'."
        )
        my_ip_str = _uid_to_ip(2, subnet)

    # ── 2. Generate ephemeral WireGuard keypair ──────────────────────────────
    with console.status("[bold]Generating ephemeral keypair…"):
        privkey, pubkey = _wg_genkey()

    # ── 3. Get TOTP from user and send ECDH knock ────────────────────────────
    if totp_code:
        otp_str = totp_code.strip()
    else:
        otp_str = Prompt.ask("[cyan]Enter TOTP from your authenticator app")

    pkt = _build_spa_packet(my_vpn_uid, otp_str, pubkey, spa_pubkey_b64)

    with console.status(f"[bold]Knocking {knock_host}:{knock_port}…"):
        try:
            sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            sock.sendto(pkt, (knock_host, knock_port))
            sock.close()
        except Exception as exc:
            console.print(f"[red]UDP send failed:[/red] {exc}")
            raise typer.Exit(1)

    # ── 4. Write restricted tunnel config + bring up ─────────────────────────
    with console.status("[bold]Bringing up tunnel (onboarding mode)…"):
        time.sleep(2.0)  # allow knock packet to be processed by sidecar

        _write_wg_conf(
            privkey=privkey,
            my_ip=my_ip_str,
            server_pubkey=server_pubkey_cfg,
            server_endpoint=server_endpoint_cfg,
            allowed_ips=f"{server_vpn_ip}/32",
        )

        result = _wg_quick("up", str(WG_CONF), check=False)
        if result.returncode != 0:
            console.print(f"[red]wg-quick up failed:[/red]\n{result.stderr.strip()}")
            raise typer.Exit(1)

    # ── 5. Wait for handshake ────────────────────────────────────────────────
    with console.status("[bold]Waiting for tunnel handshake…"):
        ok = _wait_for_handshake(timeout=20.0)

    if not ok:
        _wg_quick("down", WG_IFACE, check=False)
        console.print(
            "[red]Handshake timeout (20 s).[/red]\n"
            "Possible causes:\n"
            "  • Knock was dropped — wrong TOTP code\n"
            "  • knock_host / knock_port misconfigured (check vpn.toml)\n"
            "  • Sidecar could not add peer (check server logs)\n"
            "  • WireGuard UDP port 51820 unreachable (check firewall)"
        )
        raise typer.Exit(1)

    # ── 6. Authenticate ──────────────────────────────────────────────────────
    # NOTE: getpass MUST run outside any console.status() context — Rich's
    # live-rendering overrides terminal line-discipline and the password
    # prompt becomes invisible / unresponsive.
    internal_url = f"http://{server_vpn_ip}:{server_port}"
    token: Optional[str] = None

    creds = load_credentials()
    existing_token = creds.get("token")
    if existing_token and _token_valid(existing_token):
        token = existing_token
        console.print("[dim]Using cached credentials.[/dim]")
    else:
        console.print(f"[bold]Authenticating via VPN tunnel ({internal_url})…[/bold]")
        token = _do_login(internal_url, uid)
        if token:
            creds["token"] = token
            save_credentials(creds)

    if not token:
        _wg_quick("down", WG_IFACE, check=False)
        console.print("[red]Authentication failed. Tunnel closed.[/red]")
        raise typer.Exit(1)

    # ── 7. POST /vpn/promote ─────────────────────────────────────────────────
    with console.status("[bold]Promoting to full tunnel…"):
        try:
            internal_client = AnchorClient(server_url=internal_url, token=token)
            resp = internal_client.post("/vpn/promote")
        except AnchorClientError as exc:
            _wg_quick("down", WG_IFACE, check=False)
            console.print(f"[red]Promote request failed:[/red] {exc}")
            raise typer.Exit(1)

        if resp.status_code != 200:
            _wg_quick("down", WG_IFACE, check=False)
            detail = resp.json().get("detail", resp.status_code)
            console.print(f"[red]Promote failed:[/red] {detail}")
            raise typer.Exit(1)

        promote_data = resp.json()

    # ── 8. Rewrite config + hot-reload ───────────────────────────────────────
    assigned_ip: str = promote_data["assigned_ip"]
    server_pubkey: str = promote_data["server_pubkey"]
    server_endpoint: str = promote_data["server_endpoint"]
    lease_expires: str = promote_data["lease_expires"]
    routes_list: list[str] = promote_data.get("routes", ["0.0.0.0/0"])

    # Update cached values for next run
    cfg["server_pubkey"] = server_pubkey
    cfg["server_endpoint"] = server_endpoint
    if cfg.get("vpn_uid", 0) == 0:
        net = ipaddress.IPv4Network(subnet, strict=False)
        cfg["vpn_uid"] = int(ipaddress.IPv4Address(assigned_ip)) - int(net.network_address)
    _save_vpn_config(cfg)

    _write_wg_conf(
        privkey=privkey,
        my_ip=assigned_ip,
        server_pubkey=server_pubkey,
        server_endpoint=server_endpoint,
        allowed_ips=", ".join(routes_list),
    )

    # Hot-reload without dropping the tunnel
    syncconf = subprocess.run(
        f"sudo wg syncconf {WG_IFACE} <(sudo wg-quick strip {WG_CONF})",
        shell=True, executable="/bin/bash",
        capture_output=True, text=True,
    )
    if syncconf.returncode != 0:
        console.print(f"[yellow]wg syncconf warning:[/yellow] {syncconf.stderr.strip()}")

    # ── 9. Show summary panel ────────────────────────────────────────────────
    table = Table.grid(padding=(0, 2))
    table.add_column(style="dim")
    table.add_column()
    table.add_row("IP address", f"[green]{assigned_ip}[/green]")
    table.add_row("Routes", ", ".join(routes_list))
    table.add_row("Server endpoint", server_endpoint)
    table.add_row("Server pubkey", server_pubkey[:16] + "…")
    table.add_row("Lease expires", lease_expires.replace("T", " ").split(".")[0] + " UTC")
    table.add_row("Interface", WG_IFACE)

    console.print(Panel(table, title="[bold green]VPN Connected", border_style="green"))


@app.command("down")
def vpn_down() -> None:
    """Bring down the VPN tunnel and revoke the server lease."""
    result = _wg_quick("down", WG_IFACE, check=False)
    if result.returncode == 0:
        console.print(f"[green]Interface {WG_IFACE} down.[/green]")
    else:
        console.print(f"[yellow]{result.stderr.strip() or 'Interface not active.'}[/yellow]")

    # Best-effort: revoke lease on server
    try:
        client = AnchorClient()
        resp = client.delete("/vpn/lease")
        if resp.status_code == 200:
            console.print("[dim]Server lease revoked.[/dim]")
    except Exception:
        pass  # server unreachable or no lease — ignore


@app.command("status")
def vpn_status() -> None:
    """Show VPN status: server lease info and local wg show output."""
    # Server lease
    try:
        client = AnchorClient()
        resp = client.get("/vpn/status")
        if resp.status_code == 200:
            lease = resp.json()
            table = Table.grid(padding=(0, 2))
            table.add_column(style="dim")
            table.add_column()
            for k, v in lease.items():
                if k != "_id":
                    table.add_row(k, str(v))
            console.print(Panel(table, title="[bold]Server Lease"))
        elif resp.status_code == 404:
            console.print("[yellow]No active VPN lease on server.[/yellow]")
        else:
            console.print(f"[red]Server error:[/red] {resp.status_code}")
    except NotAuthenticatedError:
        console.print("[yellow]Not authenticated. Run: anc login[/yellow]")
    except AnchorClientError as exc:
        console.print(f"[red]Cannot reach server:[/red] {exc}")

    # Local wg status
    result = subprocess.run(
        ["sudo", "wg", "show", WG_IFACE],
        capture_output=True, text=True,
    )
    if result.returncode == 0 and result.stdout.strip():
        console.print(Panel(result.stdout.strip(), title=f"[bold]{WG_IFACE} (local)"))
    else:
        console.print(f"[dim]Interface {WG_IFACE} not active.[/dim]")
