- name: Ensure parent folder {{ local_path }}/{{ inventory_hostname }} exists
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ local_path }}/{{ inventory_hostname }}"
    state: directory
    mode: '0755'
  become: false

- name: Ensure local mount folder exists for {{ inventory_hostname }}
  delegate_to: localhost
  ansible.builtin.command:
    cmd: "mkdir -p {{ local_path }}/{{ inventory_hostname }}/command_logs"
  become: false

- name: Debug SSHFS command before execution
  delegate_to: localhost
  ansible.builtin.debug:
    msg: |
      sshfs -o IdentityFile={{ ssh_by_host[inventory_hostname].identity_file }}
            -o StrictHostKeyChecking=no
            -p {{ ssh_by_host[inventory_hostname].port }}
            {{ ssh_by_host[inventory_hostname].user }}@{{ ssh_by_host[inventory_hostname].host }}:{{ remote_path }}
            {{ local_path }}/{{ inventory_hostname }}/command_logs

- name: Mount SSHFS for {{ inventory_hostname }}
  delegate_to: localhost
  ansible.builtin.command:
    cmd: >
      sshfs
      -o IdentityFile={{ ssh_by_host[inventory_hostname].identity_file }}
      -o StrictHostKeyChecking=no
      -p {{ ssh_by_host[inventory_hostname].port }}
      {{ ssh_by_host[inventory_hostname].user }}@{{ ssh_by_host[inventory_hostname].host }}:{{ remote_path }}
      {{ local_path }}/{{ inventory_hostname }}/command_logs
  become: false
